var data = {"students":[
     {"name": "Lashanda", "last_name": "Judd", "photo":"./assets/students/one.jpg" },
     {"name": "Alisha", "last_name": "Newbill", "photo":"./assets/students/two.jpg"},
     {"name": "Corinna", "last_name": "Biggerstaff", "photo":"./assets/students/three.jpg"},
     {"name": "Ruthe", "last_name": "Reneau", "photo":"./assets/students/four.jpg" },
     {"name": "Leida", "last_name": "Stidham", "photo":"./assets/students/five.jpg" },
     {"name": "Erica", "last_name": "Heckstall", "photo":"./assets/students/six.jpg" },
     {"name": "Tereasa", "last_name": "Macbeth", "photo":"./assets/students/seven.jpg" },
     {"name": "Lilliam", "last_name": "Maricle", "photo":"./assets/students/eight.jpg" },
     {"name": "Mabel", "last_name": "Gandhi", "photo":"./assets/students/nine.jpg"},
     {"name": "Lindsy", "last_name": "Gipe", "photo":"./assets/students/ten.jpg" },
     {"name": "Marnie", "last_name": "Hille", "photo":"./assets/students/eleven.jpg" },
     {"name": "Alex", "last_name": "Ghent", "photo":"./assets/students/twelve.jpg" },
     {"name": "Danette", "last_name": "Gilcrease", "photo":"./assets/students/thirteen.jpg"},
     {"name": "Wynona", "last_name": "Dantin", "photo":"./assets/students/fourteen.jpg" },
     {"name": "Hyon", "last_name": "Leslie" , "photo":"./assets/students/fifteen.jpg" },
     {"name": "Omega", "last_name": "Schack", "photo":"./assets/students/sixteen.jpg"},
     {"name": "Rachell", "last_name": "Stahl", "photo":"./assets/students/eighteen.jpg"},
     {"name": "Viva", "last_name": "Kempker", "photo":"./assets/students/nineteen.jpg" },
     {"name": "Gretchen", "last_name": "Hedman", "photo":"./assets/students/twenty.jpg"},
     {"name": "Carolynn", "last_name": "Kincheloe", "photo":"./assets/students/twenty-one.jpg"},
     {"name": "Janice", "last_name": "Pates", "photo":"./assets/students/twenty-two.jpg" },
     {"name": "Griselda", "last_name": "Crace", "photo":"./assets/students/twenty-three.jpg" },
     {"name": "Williemae", "last_name": "Sheeran", "photo":"./assets/students/twenty-four.jpg"},
     {"name": "Haley", "last_name": "Holliday","photo":"./assets/students/twenty-five.jpg" },
     {"name": "Rayna", "last_name": "Rossiter", "photo":"./assets/students/twenty-six.jpg" },
     {"name": "Daphine", "last_name": "Leitch", "photo":"./assets/students/twenty-seven.jpg" },
     {"name": "Doreatha", "last_name": "Fecteau", "photo":"./assets/students/twenty-eight.jpg" },
     {"name": "Alina", "last_name": "Mooneyhan","photo":"./assets/students/twenty-nine.jpg" },
     {"name": "Milagros", "last_name": "Larose","photo":"./assets/students/thirty.jpg" },
     {"name": "Jennifer", "last_name": "Lopez", "photo":"./assets/students/31.jpg"},
     {"name": "Elizabeth", "last_name":"Darcy", "photo":"./assets/students/32.jpg"},
     {"name": "Lucy", "last_name": "Bullock", "photo": "./assets/students/seventeen.jpg"}
]}